# Generated by Django 4.2.5 on 2024-01-19 14:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("restaurant_service", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cook",
            name="cook_profile_picture",
            field=models.ImageField(
                default="static/assets/img/def_pfp.png", upload_to="static/assets/img"
            ),
        ),
        migrations.AddField(
            model_name="dish",
            name="picture",
            field=models.ImageField(
                default="static/assets/img/def_pfp.png", upload_to="static/assets/img"
            ),
        ),
    ]
