# Generated by Django 4.2.5 on 2024-01-19 15:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("restaurant_service", "0002_cook_cook_profile_picture_dish_picture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dish",
            name="picture",
            field=models.ImageField(
                default="static/assets/img/def_pfp.png", upload_to="cooks"
            ),
        ),
    ]
