# Generated by Django 4.2.5 on 2024-01-19 18:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("restaurant_service", "0006_alter_cook_profile_picture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cook",
            name="profile_picture",
            field=models.ImageField(
                blank=True, default="cooks/cooks/def_pfp.png", upload_to="cooks"
            ),
        ),
        migrations.AlterField(
            model_name="dish",
            name="picture",
            field=models.ImageField(
                default="cooks/cooks/def_pfp.png", upload_to="cooks"
            ),
        ),
    ]
