# Generated by Django 4.2.5 on 2024-02-09 14:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("restaurant_service", "0008_alter_cook_profile_picture_alter_dish_picture"),
    ]

    operations = [
        migrations.AddField(
            model_name="dishtype",
            name="picture",
            field=models.ImageField(
                default="picture/def_pfp.png", upload_to="dishtype"
            ),
        ),
    ]
