# Generated by Django 4.2.5 on 2024-02-25 10:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("restaurant_service", "0009_dishtype_picture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cook",
            name="profile_picture",
            field=models.ImageField(
                blank=True, default="avatars/def_pfp.png", upload_to="avatars"
            ),
        ),
        migrations.AlterField(
            model_name="dish",
            name="picture",
            field=models.ImageField(default="avatars/def_pfp.png", upload_to="dish"),
        ),
        migrations.AlterField(
            model_name="dishtype",
            name="picture",
            field=models.ImageField(
                default="avatars/def_pfp.png", upload_to="dishtype"
            ),
        ),
    ]
