# Generated by Django 4.2.5 on 2024-02-25 11:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("restaurant_service", "0012_alter_dish_picture_alter_dishtype_picture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cook",
            name="profile_picture",
            field=models.ImageField(
                blank=True, default="picture/def_pfp.png", upload_to="media/avatars"
            ),
        ),
        migrations.AlterField(
            model_name="dish",
            name="picture",
            field=models.ImageField(
                blank=True, default="picture/def_pfp.png", upload_to="media/dish"
            ),
        ),
    ]
