# Generated by Django 4.2.5 on 2024-02-28 17:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("restaurant_service", "0013_alter_cook_profile_picture_alter_dish_picture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cook",
            name="profile_picture",
            field=models.ImageField(
                blank=True, default="picture/def_pfp.png", upload_to="avatars/"
            ),
        ),
        migrations.AlterField(
            model_name="dish",
            name="picture",
            field=models.ImageField(
                blank=True, default="picture/def_pfp.png", upload_to="dish/"
            ),
        ),
        migrations.AlterField(
            model_name="dishtype",
            name="picture",
            field=models.ImageField(
                blank=True, default="picture/def_pfp.png", upload_to="dishtype/"
            ),
        ),
    ]
