# Generated by Django 4.2.5 on 2024-03-02 18:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "restaurant_service",
            "0014_alter_cook_profile_picture_alter_dish_picture_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dishtype",
            name="picture",
        ),
    ]
