# Generated by Django 4.2.5 on 2024-03-02 19:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("restaurant_service", "0015_remove_dishtype_picture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cook",
            name="profile_picture",
            field=models.ImageField(
                blank=True, default="pictures/def_pfp.png", upload_to="avatars/"
            ),
        ),
        migrations.AlterField(
            model_name="dish",
            name="picture",
            field=models.ImageField(
                blank=True, default="pictures/def_pfp.png", upload_to="dish/"
            ),
        ),
    ]
