# Generated by Django 4.2.5 on 2024-03-03 15:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("restaurant_service", "0016_alter_cook_profile_picture_alter_dish_picture"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cook",
            name="profile_picture",
        ),
        migrations.RemoveField(
            model_name="dish",
            name="picture",
        ),
    ]
